name: Feature Completed Workflow

on:
  push:
    tags:
      - 'feature-completed-*'

jobs:
  check_feature_completion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Branch Name
        id: extract_branch
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git tag -l --format='%(contents:subject)' $tag
          TAG_DESCRIPTION=$(git tag -l --format='%(contents:subject)' $tag)
          echo "Tag Description: $TAG_DESCRIPTION"
          
          # Extract branch name from the description using grep and a regular expression
          BRANCH_NAME=$(echo "$TAG_DESCRIPTION" | grep -oP 'Branch: \K.*')
          echo "Branch Name: $BRANCH_NAME"
          # Set the extracted branch name as an output for later steps
          echo "branch_name=$BRANCH_NAME" >> "$GITHUB_STATE"
      - name: Create Pull Request to Test
        run: |
          echo "$branch_name"
          gh pr create --base test --head "$branch_name" --title "Feature: Your Feature Name" --body "Description of your feature changes"

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
