name: Feature Completed Workflow

on:
  push:
    tags:
      - 'feature-completed-*'

jobs:
  check_feature_completion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if a feature is completed
        id: extract_branch
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git tag -l --format='%(contents:subject)' $tag
          TAG_DESCRIPTION=$(git tag -l --format='%(contents:subject)' $tag)
          echo "Tag Description: $TAG_DESCRIPTION"
          
          # Extract branch name from the description using grep and a regular expression
          BRANCH_NAME=$(echo "$TAG_DESCRIPTION" | grep -oP 'Branch: \K.*')
          echo "Branch Name: $BRANCH_NAME"
          # Set the extracted branch name as an output for later steps
          echo "::set-output name=branch_name::$BRANCH_NAME"

      - name: Create Pull Request to Test
        run: |
          BRANCH_NAME="${{ steps.extract_branch.outputs.branch_name }}"
          git checkout -b $BRANCH_NAME
          git push --set-upstream origin $BRANCH_NAME
          gh pr create --base test --head $BRANCH_NAME --title "Feature: Your Feature Name" --body "Description of your feature changes"

      - name: Create Pull Request to Main
        run: |
          BRANCH_NAME="${{ steps.extract_branch.outputs.branch_name }}"
          git checkout -b $BRANCH_NAME
          git push --set-upstream origin $BRANCH_NAME
          gh pr create --base main --head $BRANCH_NAME --title "Feature: Your Feature Name" --body "Description of your feature changes"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
